baseURL: https://gianmarcoserra.netlify.app/
languageCode: en-us
title: Website for Gian Marco Serra
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get to know Gian Marco
    subtitle: |-
    title: Hi, my name is Gian Marco, pleased to meet you!
  blog: {}
  contact:
    address:
      - city: Bologna
        country: Italy
        street: Via Parigi
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: serragianmarco747@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (0039) 333 2911956
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Gian Marco Serra Enterprises
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/gianma747
     # - icon: fa-facebook
      #  label: Facebook
       # url: https://www.facebook.com
     # - icon: fa-instagram
      #  label: Instagram
      #  url: https://www.instagram.com #
      - icon: fa-github
        label: GitHub
        url: https://github.com/gianma747
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/serra1999
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: senzacravatta.jpg
        subtitle: Download  Gian Marco's CV and other endeavours
        title: CV
        url: docs/cv.pdf
      - image: DSC01525.JPG
        subtitle: Witness Gian Marco's backpacking journey in the tongue of the troll...
        title:  Norway
        url: blogs/norway
      - image: spotify.jpg
        subtitle: See a breakdown of Gian Marco's music tastes done through R
        title: Gian Marco's Music
        url: blogs/myspotify
      - image: books.jpg
        subtitle: Read all about Gian Marco's book recommendations
        title: Books
        url: blogs/books
    #  - image: pasta.jpg
     #   subtitle: Get to appreciate Gian Marco's London restaurant recommendations
      #  title: Foodie
       # url: blogs/foodstuff
    #  - image: pic06.jpg
     #   subtitle: Enjoy some other stuff Gian Marco has done with R
      #  title: R Project 2 
       # url: blogs/r-project-second
  two:
    buttonText: Gian's OnlyFans
    enable: yes
    subtitle: "Are You still curious about Gian Marco's life and endeavours?\n
      Then You should consider minding your own business...but since You are here,
      please take advantage and proceed to the only fans section: Gian Marco's blog. \n    
      Here Gian Marco will post semi-regular updates on his life to display how much cooler it is than Yours ;P \n 
      Any of the pictures displayed here will be the result of an accurate selection made to ensure than any viewer feels miserable when looking at them, in the hopes that You stop coming here.\n 
      Have a nice life mate."
    title: Gian Marco's message
    url: blogs